### ISSUE TITLE
Fix master build for gatling-imap

### ISSUE THREAD

**Issue by Arsnael** [linagora/gatling-imap#78]
Master build since end of june seems failing for gatlin-imap. It hangs forever on the test `ImapGetQuotaScenarioJamesIT`

The fail after investigating a bit seems occuring  when we try to get the quotas.

Stacktrace on tmail backend side:

java.lang.IllegalArgumentException: username should not be null or empty after being trimmed                                                                                                                       
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)                                                                                                                              
        at org.apache.james.core.Username.of(Username.java:36)                             
        at org.apache.james.mailbox.store.quota.DefaultUserQuotaRootResolver$DefaultQuotaRootDeserializer.fromString(DefaultUserQuotaRootResolver.java:59)
        at org.apache.james.mailbox.store.quota.DefaultUserQuotaRootResolver.fromString(DefaultUserQuotaRootResolver.java:155)
        at org.apache.james.imap.processor.GetQuotaProcessor.processRequestReactive(GetQuotaProcessor.java:76)   
        at org.apache.james.imap.processor.GetQuotaProcessor.processRequestReactive(GetQuotaProcessor.java:53)
        at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:99)    
        at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:76)    
        at org.apache.james.imap.processor.base.AbstractProcessor.processReactive(AbstractProcessor.java:55)
        at org.apache.james.imap.processor.DefaultProcessor.processReactive(DefaultProcessor.java:156)                                                                                                             
        at org.apache.james.imapserver.netty.ImapChannelUpstreamHandler.channelRead(ImapChannelUpstreamHandler.java:415)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)  
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Unknown Source)

Also when looking what work around quotas classes was done around that time, found that ocmmit => https://github.com/apache/james-project/pull/2303/commits/c6962f737f2162a1dc72eb05a509f83dc0cac4dc

Reverting the code in `DefaultUserQuotaRootResolver`, rebuilding the image and replaying the test make it green.

I really could not understand why though it seems gatling imap does not like it when trying to get quotas

Need to investigate more and find a fix for this.

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/2477

Should fix the build. And also feels like that edge case was missed after the refactoring, would feel logical to throw here in case there is no separator in serialized quota root as then the rest of the code can't extract a username if only one part.

**Comment by Arsnael** [comment]
However I don't think the get quota command was done correctly in gatling imap, proof is we expect it to fail in the scenario: https://github.com/linagora/gatling-imap/blob/master/src/main/scala-2.13/com/linagora/gatling/imap/scenario/ImapGetQuotaScenario.scala#L16

Same with set quota actually... 

Will have a look

**Comment by Arsnael** [comment]
https://github.com/linagora/gatling-imap/pull/79
